# Generated by Django 5.2.6 on 2025-09-24 01:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=64, null=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('teacher_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('student_code', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('class_fk', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.class')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('teacher_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('class_fk', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='api.class')),
                ('student_fk', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='api.student')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student_fk', 'class_fk', 'date'), name='uniq_attendance_student_class_date')],
            },
        ),
    ]
