# Generated by Django 5.2.6 on 2025-09-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='academic_year_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
